version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: cofrinho_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: database_password
      POSTGRES_DB: cofrinho
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cofrinho_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: cofrinho_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cofrinho.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - cofrinho_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  cofrinho_network:
    driver: bridge